/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.mashov.avro.services.bla.samples.structures;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7645441007266949181L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle\",\"namespace\":\"org.mashov.avro.services.bla.samples.structures\",\"fields\":[{\"name\":\"reportingSystemId\",\"type\":\"long\",\"default\":0},{\"name\":\"callSign\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"privateNetworkNumber\",\"type\":\"long\",\"default\":0},{\"name\":\"formNumber\",\"type\":\"int\",\"default\":-1},{\"name\":\"blaBla\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long reportingSystemId;
  @Deprecated public java.lang.String callSign;
  @Deprecated public long privateNetworkNumber;
  @Deprecated public int formNumber;
  @Deprecated public java.lang.Integer blaBla;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle() {}

  /**
   * All-args constructor.
   * @param reportingSystemId The new value for reportingSystemId
   * @param callSign The new value for callSign
   * @param privateNetworkNumber The new value for privateNetworkNumber
   * @param formNumber The new value for formNumber
   * @param blaBla The new value for blaBla
   */
  public InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle(java.lang.Long reportingSystemId, java.lang.String callSign, java.lang.Long privateNetworkNumber, java.lang.Integer formNumber, java.lang.Integer blaBla) {
    this.reportingSystemId = reportingSystemId;
    this.callSign = callSign;
    this.privateNetworkNumber = privateNetworkNumber;
    this.formNumber = formNumber;
    this.blaBla = blaBla;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return reportingSystemId;
    case 1: return callSign;
    case 2: return privateNetworkNumber;
    case 3: return formNumber;
    case 4: return blaBla;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: reportingSystemId = (java.lang.Long)value$; break;
    case 1: callSign = (java.lang.String)value$; break;
    case 2: privateNetworkNumber = (java.lang.Long)value$; break;
    case 3: formNumber = (java.lang.Integer)value$; break;
    case 4: blaBla = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'reportingSystemId' field.
   * @return The value of the 'reportingSystemId' field.
   */
  public java.lang.Long getReportingSystemId() {
    return reportingSystemId;
  }

  /**
   * Sets the value of the 'reportingSystemId' field.
   * @param value the value to set.
   */
  public void setReportingSystemId(java.lang.Long value) {
    this.reportingSystemId = value;
  }

  /**
   * Gets the value of the 'callSign' field.
   * @return The value of the 'callSign' field.
   */
  public java.lang.String getCallSign() {
    return callSign;
  }

  /**
   * Sets the value of the 'callSign' field.
   * @param value the value to set.
   */
  public void setCallSign(java.lang.String value) {
    this.callSign = value;
  }

  /**
   * Gets the value of the 'privateNetworkNumber' field.
   * @return The value of the 'privateNetworkNumber' field.
   */
  public java.lang.Long getPrivateNetworkNumber() {
    return privateNetworkNumber;
  }

  /**
   * Sets the value of the 'privateNetworkNumber' field.
   * @param value the value to set.
   */
  public void setPrivateNetworkNumber(java.lang.Long value) {
    this.privateNetworkNumber = value;
  }

  /**
   * Gets the value of the 'formNumber' field.
   * @return The value of the 'formNumber' field.
   */
  public java.lang.Integer getFormNumber() {
    return formNumber;
  }

  /**
   * Sets the value of the 'formNumber' field.
   * @param value the value to set.
   */
  public void setFormNumber(java.lang.Integer value) {
    this.formNumber = value;
  }

  /**
   * Gets the value of the 'blaBla' field.
   * @return The value of the 'blaBla' field.
   */
  public java.lang.Integer getBlaBla() {
    return blaBla;
  }

  /**
   * Sets the value of the 'blaBla' field.
   * @param value the value to set.
   */
  public void setBlaBla(java.lang.Integer value) {
    this.blaBla = value;
  }

  /**
   * Creates a new InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle RecordBuilder.
   * @return A new InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle RecordBuilder
   */
  public static org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder newBuilder() {
    return new org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder();
  }

  /**
   * Creates a new InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle RecordBuilder
   */
  public static org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder newBuilder(org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder other) {
    return new org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder(other);
  }

  /**
   * Creates a new InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle RecordBuilder by copying an existing InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle instance.
   * @param other The existing instance to copy.
   * @return A new InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle RecordBuilder
   */
  public static org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder newBuilder(org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle other) {
    return new org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder(other);
  }

  /**
   * RecordBuilder for InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle>
    implements org.apache.avro.data.RecordBuilder<InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle> {

    private long reportingSystemId;
    private java.lang.String callSign;
    private long privateNetworkNumber;
    private int formNumber;
    private java.lang.Integer blaBla;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.reportingSystemId)) {
        this.reportingSystemId = data().deepCopy(fields()[0].schema(), other.reportingSystemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.callSign)) {
        this.callSign = data().deepCopy(fields()[1].schema(), other.callSign);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.privateNetworkNumber)) {
        this.privateNetworkNumber = data().deepCopy(fields()[2].schema(), other.privateNetworkNumber);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.formNumber)) {
        this.formNumber = data().deepCopy(fields()[3].schema(), other.formNumber);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.blaBla)) {
        this.blaBla = data().deepCopy(fields()[4].schema(), other.blaBla);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle instance
     * @param other The existing instance to copy.
     */
    private Builder(org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.reportingSystemId)) {
        this.reportingSystemId = data().deepCopy(fields()[0].schema(), other.reportingSystemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.callSign)) {
        this.callSign = data().deepCopy(fields()[1].schema(), other.callSign);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.privateNetworkNumber)) {
        this.privateNetworkNumber = data().deepCopy(fields()[2].schema(), other.privateNetworkNumber);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.formNumber)) {
        this.formNumber = data().deepCopy(fields()[3].schema(), other.formNumber);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.blaBla)) {
        this.blaBla = data().deepCopy(fields()[4].schema(), other.blaBla);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'reportingSystemId' field.
      * @return The value.
      */
    public java.lang.Long getReportingSystemId() {
      return reportingSystemId;
    }

    /**
      * Sets the value of the 'reportingSystemId' field.
      * @param value The value of 'reportingSystemId'.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder setReportingSystemId(long value) {
      validate(fields()[0], value);
      this.reportingSystemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'reportingSystemId' field has been set.
      * @return True if the 'reportingSystemId' field has been set, false otherwise.
      */
    public boolean hasReportingSystemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'reportingSystemId' field.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder clearReportingSystemId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'callSign' field.
      * @return The value.
      */
    public java.lang.String getCallSign() {
      return callSign;
    }

    /**
      * Sets the value of the 'callSign' field.
      * @param value The value of 'callSign'.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder setCallSign(java.lang.String value) {
      validate(fields()[1], value);
      this.callSign = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'callSign' field has been set.
      * @return True if the 'callSign' field has been set, false otherwise.
      */
    public boolean hasCallSign() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'callSign' field.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder clearCallSign() {
      callSign = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'privateNetworkNumber' field.
      * @return The value.
      */
    public java.lang.Long getPrivateNetworkNumber() {
      return privateNetworkNumber;
    }

    /**
      * Sets the value of the 'privateNetworkNumber' field.
      * @param value The value of 'privateNetworkNumber'.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder setPrivateNetworkNumber(long value) {
      validate(fields()[2], value);
      this.privateNetworkNumber = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'privateNetworkNumber' field has been set.
      * @return True if the 'privateNetworkNumber' field has been set, false otherwise.
      */
    public boolean hasPrivateNetworkNumber() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'privateNetworkNumber' field.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder clearPrivateNetworkNumber() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'formNumber' field.
      * @return The value.
      */
    public java.lang.Integer getFormNumber() {
      return formNumber;
    }

    /**
      * Sets the value of the 'formNumber' field.
      * @param value The value of 'formNumber'.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder setFormNumber(int value) {
      validate(fields()[3], value);
      this.formNumber = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'formNumber' field has been set.
      * @return True if the 'formNumber' field has been set, false otherwise.
      */
    public boolean hasFormNumber() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'formNumber' field.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder clearFormNumber() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'blaBla' field.
      * @return The value.
      */
    public java.lang.Integer getBlaBla() {
      return blaBla;
    }

    /**
      * Sets the value of the 'blaBla' field.
      * @param value The value of 'blaBla'.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder setBlaBla(java.lang.Integer value) {
      validate(fields()[4], value);
      this.blaBla = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'blaBla' field has been set.
      * @return True if the 'blaBla' field has been set, false otherwise.
      */
    public boolean hasBlaBla() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'blaBla' field.
      * @return This builder.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle.Builder clearBlaBla() {
      blaBla = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle build() {
      try {
        InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle record = new InitializeParametersDtDeletionOfNonNullableFieldAtTheMiddle();
        record.reportingSystemId = fieldSetFlags()[0] ? this.reportingSystemId : (java.lang.Long) defaultValue(fields()[0]);
        record.callSign = fieldSetFlags()[1] ? this.callSign : (java.lang.String) defaultValue(fields()[1]);
        record.privateNetworkNumber = fieldSetFlags()[2] ? this.privateNetworkNumber : (java.lang.Long) defaultValue(fields()[2]);
        record.formNumber = fieldSetFlags()[3] ? this.formNumber : (java.lang.Integer) defaultValue(fields()[3]);
        record.blaBla = fieldSetFlags()[4] ? this.blaBla : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
