/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.mashov.bla.schema.data.entity;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** blablablabla */
@org.apache.avro.specific.AvroGenerated
public class bgUnion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8984451806381821711L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"bgUnion\",\"namespace\":\"org.mashov.bla.schema.data.entity\",\"doc\":\"blablablabla\",\"fields\":[{\"name\":\"first\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"bgRecord\",\"doc\":\"blablablabla\",\"fields\":[{\"name\":\"first\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"bbbbbbb\",\"default\":null},{\"name\":\"second\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"bbbbbbb\",\"default\":null},{\"name\":\"third\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"bbbbbbb\",\"default\":null},{\"name\":\"forth\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"bbbbbbb\",\"default\":\"defaultEmpty\"}]}],\"doc\":\"bbbbbbb\",\"default\":null},{\"name\":\"second\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"InitializeParametersDt\",\"namespace\":\"org.mashov.avro.services.bla.samples.structures\",\"fields\":[{\"name\":\"reportingSystemId\",\"type\":\"long\",\"default\":0},{\"name\":\"callSign\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"privateNetworkNumber\",\"type\":\"long\",\"default\":0},{\"name\":\"globalNetworkNumber\",\"type\":\"long\",\"default\":0},{\"name\":\"blaBlaSecond\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"formNumber\",\"type\":\"int\",\"default\":-1},{\"name\":\"blaBla\",\"type\":[\"null\",\"int\"],\"default\":null}]}],\"doc\":\"bbbbbbb\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** bbbbbbb */
  @Deprecated public org.mashov.bla.schema.data.entity.bgRecord first;
  /** bbbbbbb */
  @Deprecated public org.mashov.avro.services.bla.samples.structures.InitializeParametersDt second;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public bgUnion() {}

  /**
   * All-args constructor.
   * @param first bbbbbbb
   * @param second bbbbbbb
   */
  public bgUnion(org.mashov.bla.schema.data.entity.bgRecord first, org.mashov.avro.services.bla.samples.structures.InitializeParametersDt second) {
    this.first = first;
    this.second = second;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return first;
    case 1: return second;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: first = (org.mashov.bla.schema.data.entity.bgRecord)value$; break;
    case 1: second = (org.mashov.avro.services.bla.samples.structures.InitializeParametersDt)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'first' field.
   * @return bbbbbbb
   */
  public org.mashov.bla.schema.data.entity.bgRecord getFirst() {
    return first;
  }

  /**
   * Sets the value of the 'first' field.
   * bbbbbbb
   * @param value the value to set.
   */
  public void setFirst(org.mashov.bla.schema.data.entity.bgRecord value) {
    this.first = value;
  }

  /**
   * Gets the value of the 'second' field.
   * @return bbbbbbb
   */
  public org.mashov.avro.services.bla.samples.structures.InitializeParametersDt getSecond() {
    return second;
  }

  /**
   * Sets the value of the 'second' field.
   * bbbbbbb
   * @param value the value to set.
   */
  public void setSecond(org.mashov.avro.services.bla.samples.structures.InitializeParametersDt value) {
    this.second = value;
  }

  /**
   * Creates a new bgUnion RecordBuilder.
   * @return A new bgUnion RecordBuilder
   */
  public static org.mashov.bla.schema.data.entity.bgUnion.Builder newBuilder() {
    return new org.mashov.bla.schema.data.entity.bgUnion.Builder();
  }

  /**
   * Creates a new bgUnion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new bgUnion RecordBuilder
   */
  public static org.mashov.bla.schema.data.entity.bgUnion.Builder newBuilder(org.mashov.bla.schema.data.entity.bgUnion.Builder other) {
    return new org.mashov.bla.schema.data.entity.bgUnion.Builder(other);
  }

  /**
   * Creates a new bgUnion RecordBuilder by copying an existing bgUnion instance.
   * @param other The existing instance to copy.
   * @return A new bgUnion RecordBuilder
   */
  public static org.mashov.bla.schema.data.entity.bgUnion.Builder newBuilder(org.mashov.bla.schema.data.entity.bgUnion other) {
    return new org.mashov.bla.schema.data.entity.bgUnion.Builder(other);
  }

  /**
   * RecordBuilder for bgUnion instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<bgUnion>
    implements org.apache.avro.data.RecordBuilder<bgUnion> {

    /** bbbbbbb */
    private org.mashov.bla.schema.data.entity.bgRecord first;
    private org.mashov.bla.schema.data.entity.bgRecord.Builder firstBuilder;
    /** bbbbbbb */
    private org.mashov.avro.services.bla.samples.structures.InitializeParametersDt second;
    private org.mashov.avro.services.bla.samples.structures.InitializeParametersDt.Builder secondBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.mashov.bla.schema.data.entity.bgUnion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.first)) {
        this.first = data().deepCopy(fields()[0].schema(), other.first);
        fieldSetFlags()[0] = true;
      }
      if (other.hasFirstBuilder()) {
        this.firstBuilder = org.mashov.bla.schema.data.entity.bgRecord.newBuilder(other.getFirstBuilder());
      }
      if (isValidValue(fields()[1], other.second)) {
        this.second = data().deepCopy(fields()[1].schema(), other.second);
        fieldSetFlags()[1] = true;
      }
      if (other.hasSecondBuilder()) {
        this.secondBuilder = org.mashov.avro.services.bla.samples.structures.InitializeParametersDt.newBuilder(other.getSecondBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing bgUnion instance
     * @param other The existing instance to copy.
     */
    private Builder(org.mashov.bla.schema.data.entity.bgUnion other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.first)) {
        this.first = data().deepCopy(fields()[0].schema(), other.first);
        fieldSetFlags()[0] = true;
      }
      this.firstBuilder = null;
      if (isValidValue(fields()[1], other.second)) {
        this.second = data().deepCopy(fields()[1].schema(), other.second);
        fieldSetFlags()[1] = true;
      }
      this.secondBuilder = null;
    }

    /**
      * Gets the value of the 'first' field.
      * bbbbbbb
      * @return The value.
      */
    public org.mashov.bla.schema.data.entity.bgRecord getFirst() {
      return first;
    }

    /**
      * Sets the value of the 'first' field.
      * bbbbbbb
      * @param value The value of 'first'.
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.bgUnion.Builder setFirst(org.mashov.bla.schema.data.entity.bgRecord value) {
      validate(fields()[0], value);
      this.firstBuilder = null;
      this.first = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'first' field has been set.
      * bbbbbbb
      * @return True if the 'first' field has been set, false otherwise.
      */
    public boolean hasFirst() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'first' field and creates one if it doesn't exist yet.
     * bbbbbbb
     * @return This builder.
     */
    public org.mashov.bla.schema.data.entity.bgRecord.Builder getFirstBuilder() {
      if (firstBuilder == null) {
        if (hasFirst()) {
          setFirstBuilder(org.mashov.bla.schema.data.entity.bgRecord.newBuilder(first));
        } else {
          setFirstBuilder(org.mashov.bla.schema.data.entity.bgRecord.newBuilder());
        }
      }
      return firstBuilder;
    }

    /**
     * Sets the Builder instance for the 'first' field
     * bbbbbbb
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.mashov.bla.schema.data.entity.bgUnion.Builder setFirstBuilder(org.mashov.bla.schema.data.entity.bgRecord.Builder value) {
      clearFirst();
      firstBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'first' field has an active Builder instance
     * bbbbbbb
     * @return True if the 'first' field has an active Builder instance
     */
    public boolean hasFirstBuilder() {
      return firstBuilder != null;
    }

    /**
      * Clears the value of the 'first' field.
      * bbbbbbb
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.bgUnion.Builder clearFirst() {
      first = null;
      firstBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'second' field.
      * bbbbbbb
      * @return The value.
      */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDt getSecond() {
      return second;
    }

    /**
      * Sets the value of the 'second' field.
      * bbbbbbb
      * @param value The value of 'second'.
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.bgUnion.Builder setSecond(org.mashov.avro.services.bla.samples.structures.InitializeParametersDt value) {
      validate(fields()[1], value);
      this.secondBuilder = null;
      this.second = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'second' field has been set.
      * bbbbbbb
      * @return True if the 'second' field has been set, false otherwise.
      */
    public boolean hasSecond() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'second' field and creates one if it doesn't exist yet.
     * bbbbbbb
     * @return This builder.
     */
    public org.mashov.avro.services.bla.samples.structures.InitializeParametersDt.Builder getSecondBuilder() {
      if (secondBuilder == null) {
        if (hasSecond()) {
          setSecondBuilder(org.mashov.avro.services.bla.samples.structures.InitializeParametersDt.newBuilder(second));
        } else {
          setSecondBuilder(org.mashov.avro.services.bla.samples.structures.InitializeParametersDt.newBuilder());
        }
      }
      return secondBuilder;
    }

    /**
     * Sets the Builder instance for the 'second' field
     * bbbbbbb
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.mashov.bla.schema.data.entity.bgUnion.Builder setSecondBuilder(org.mashov.avro.services.bla.samples.structures.InitializeParametersDt.Builder value) {
      clearSecond();
      secondBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'second' field has an active Builder instance
     * bbbbbbb
     * @return True if the 'second' field has an active Builder instance
     */
    public boolean hasSecondBuilder() {
      return secondBuilder != null;
    }

    /**
      * Clears the value of the 'second' field.
      * bbbbbbb
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.bgUnion.Builder clearSecond() {
      second = null;
      secondBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public bgUnion build() {
      try {
        bgUnion record = new bgUnion();
        if (firstBuilder != null) {
          record.first = this.firstBuilder.build();
        } else {
          record.first = fieldSetFlags()[0] ? this.first : (org.mashov.bla.schema.data.entity.bgRecord) defaultValue(fields()[0]);
        }
        if (secondBuilder != null) {
          record.second = this.secondBuilder.build();
        } else {
          record.second = fieldSetFlags()[1] ? this.second : (org.mashov.avro.services.bla.samples.structures.InitializeParametersDt) defaultValue(fields()[1]);
        }
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
