/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.mashov.bla.schema.data.entity;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** blablablabla */
@org.apache.avro.specific.AvroGenerated
public class InitializeParametersDtDeletionOfNullableFieldAtTheBeggining extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6551367577218529277L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InitializeParametersDtDeletionOfNullableFieldAtTheBeggining\",\"namespace\":\"org.mashov.bla.schema.data.entity\",\"doc\":\"blablablabla\",\"fields\":[{\"name\":\"second\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"bbbbbbb\",\"default\":null},{\"name\":\"third\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"bbbbbbb\",\"default\":null},{\"name\":\"forth\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"bbbbbbb\",\"default\":\"defaultEmpty\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** bbbbbbb */
  @Deprecated public java.lang.String second;
  /** bbbbbbb */
  @Deprecated public java.lang.String third;
  /** bbbbbbb */
  @Deprecated public java.lang.String forth;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InitializeParametersDtDeletionOfNullableFieldAtTheBeggining() {}

  /**
   * All-args constructor.
   * @param second bbbbbbb
   * @param third bbbbbbb
   * @param forth bbbbbbb
   */
  public InitializeParametersDtDeletionOfNullableFieldAtTheBeggining(java.lang.String second, java.lang.String third, java.lang.String forth) {
    this.second = second;
    this.third = third;
    this.forth = forth;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return second;
    case 1: return third;
    case 2: return forth;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: second = (java.lang.String)value$; break;
    case 1: third = (java.lang.String)value$; break;
    case 2: forth = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'second' field.
   * @return bbbbbbb
   */
  public java.lang.String getSecond() {
    return second;
  }

  /**
   * Sets the value of the 'second' field.
   * bbbbbbb
   * @param value the value to set.
   */
  public void setSecond(java.lang.String value) {
    this.second = value;
  }

  /**
   * Gets the value of the 'third' field.
   * @return bbbbbbb
   */
  public java.lang.String getThird() {
    return third;
  }

  /**
   * Sets the value of the 'third' field.
   * bbbbbbb
   * @param value the value to set.
   */
  public void setThird(java.lang.String value) {
    this.third = value;
  }

  /**
   * Gets the value of the 'forth' field.
   * @return bbbbbbb
   */
  public java.lang.String getForth() {
    return forth;
  }

  /**
   * Sets the value of the 'forth' field.
   * bbbbbbb
   * @param value the value to set.
   */
  public void setForth(java.lang.String value) {
    this.forth = value;
  }

  /**
   * Creates a new InitializeParametersDtDeletionOfNullableFieldAtTheBeggining RecordBuilder.
   * @return A new InitializeParametersDtDeletionOfNullableFieldAtTheBeggining RecordBuilder
   */
  public static org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder newBuilder() {
    return new org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder();
  }

  /**
   * Creates a new InitializeParametersDtDeletionOfNullableFieldAtTheBeggining RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InitializeParametersDtDeletionOfNullableFieldAtTheBeggining RecordBuilder
   */
  public static org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder newBuilder(org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder other) {
    return new org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder(other);
  }

  /**
   * Creates a new InitializeParametersDtDeletionOfNullableFieldAtTheBeggining RecordBuilder by copying an existing InitializeParametersDtDeletionOfNullableFieldAtTheBeggining instance.
   * @param other The existing instance to copy.
   * @return A new InitializeParametersDtDeletionOfNullableFieldAtTheBeggining RecordBuilder
   */
  public static org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder newBuilder(org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining other) {
    return new org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder(other);
  }

  /**
   * RecordBuilder for InitializeParametersDtDeletionOfNullableFieldAtTheBeggining instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InitializeParametersDtDeletionOfNullableFieldAtTheBeggining>
    implements org.apache.avro.data.RecordBuilder<InitializeParametersDtDeletionOfNullableFieldAtTheBeggining> {

    /** bbbbbbb */
    private java.lang.String second;
    /** bbbbbbb */
    private java.lang.String third;
    /** bbbbbbb */
    private java.lang.String forth;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.second)) {
        this.second = data().deepCopy(fields()[0].schema(), other.second);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.third)) {
        this.third = data().deepCopy(fields()[1].schema(), other.third);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.forth)) {
        this.forth = data().deepCopy(fields()[2].schema(), other.forth);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing InitializeParametersDtDeletionOfNullableFieldAtTheBeggining instance
     * @param other The existing instance to copy.
     */
    private Builder(org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.second)) {
        this.second = data().deepCopy(fields()[0].schema(), other.second);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.third)) {
        this.third = data().deepCopy(fields()[1].schema(), other.third);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.forth)) {
        this.forth = data().deepCopy(fields()[2].schema(), other.forth);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'second' field.
      * bbbbbbb
      * @return The value.
      */
    public java.lang.String getSecond() {
      return second;
    }

    /**
      * Sets the value of the 'second' field.
      * bbbbbbb
      * @param value The value of 'second'.
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder setSecond(java.lang.String value) {
      validate(fields()[0], value);
      this.second = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'second' field has been set.
      * bbbbbbb
      * @return True if the 'second' field has been set, false otherwise.
      */
    public boolean hasSecond() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'second' field.
      * bbbbbbb
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder clearSecond() {
      second = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'third' field.
      * bbbbbbb
      * @return The value.
      */
    public java.lang.String getThird() {
      return third;
    }

    /**
      * Sets the value of the 'third' field.
      * bbbbbbb
      * @param value The value of 'third'.
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder setThird(java.lang.String value) {
      validate(fields()[1], value);
      this.third = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'third' field has been set.
      * bbbbbbb
      * @return True if the 'third' field has been set, false otherwise.
      */
    public boolean hasThird() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'third' field.
      * bbbbbbb
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder clearThird() {
      third = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'forth' field.
      * bbbbbbb
      * @return The value.
      */
    public java.lang.String getForth() {
      return forth;
    }

    /**
      * Sets the value of the 'forth' field.
      * bbbbbbb
      * @param value The value of 'forth'.
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder setForth(java.lang.String value) {
      validate(fields()[2], value);
      this.forth = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'forth' field has been set.
      * bbbbbbb
      * @return True if the 'forth' field has been set, false otherwise.
      */
    public boolean hasForth() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'forth' field.
      * bbbbbbb
      * @return This builder.
      */
    public org.mashov.bla.schema.data.entity.InitializeParametersDtDeletionOfNullableFieldAtTheBeggining.Builder clearForth() {
      forth = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public InitializeParametersDtDeletionOfNullableFieldAtTheBeggining build() {
      try {
        InitializeParametersDtDeletionOfNullableFieldAtTheBeggining record = new InitializeParametersDtDeletionOfNullableFieldAtTheBeggining();
        record.second = fieldSetFlags()[0] ? this.second : (java.lang.String) defaultValue(fields()[0]);
        record.third = fieldSetFlags()[1] ? this.third : (java.lang.String) defaultValue(fields()[1]);
        record.forth = fieldSetFlags()[2] ? this.forth : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
