/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.mashov.bla.blu.bly.enums;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MyEnumBreakOne {
  NONE, A, C, B  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MyEnumBreakOne\",\"namespace\":\"org.mashov.bla.blu.bly.enums\",\"symbols\":[\"NONE\",\"A\",\"C\",\"B\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
