/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.mashov.bla.blu.bly.enums;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SystemName {
  NONE, A, B, C  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SystemName\",\"namespace\":\"org.mashov.bla.blu.bly.enums\",\"symbols\":[\"NONE\",\"A\",\"B\",\"C\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
